apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  namespace: default
spec:
  selector:
    app: haproxy
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: prometheus
    protocol: TCP
    port: 8404
    targetPort: 8404
  type: LoadBalancer
