apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
        log stdout format raw local0

    defaults
        log global
        mode http
        option httplog
        option dontlognull
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms

    frontend http-in
        bind *:8080
        default_backend teastore-backend

    backend teastore-backend
        balance roundrobin
        server teastore-webui-1 10.244.0.89:8080 check

    frontend stats
        bind *:8404
        mode http
        http-request use-service prometheus-exporter if { path /metrics }
        no log
