apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: haproxy-ingress-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: haproxy-kubernetes-ingress
  namespace: default
roleRef:
  kind: ClusterRole
  name: haproxy-ingress-clusterrole
  apiGroup: rbac.authorization.k8s.io

