apiVersion: v1
kind: Service
metadata:
  name: transformer-service
  namespace: default
spec:
  selector:
    app: transformer-service
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: metrics
      protocol: TCP
      port: 8002
      targetPort: 8002
  type: LoadBalancer
